import jsPDF from 'jspdf';
import Papa from 'papaparse';

export function downloadJSON(report) {
  const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `bias_report_${report.id}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadCSV(report) {
  const rows = report.frames.map(f => ({
    screen_id: f.screen_id,
    timestamp: f.timestamp || 'N/A',
    gender: f.gender,
    role: f.role,
    activity: f.activity,
    emotion: f.emotion,
    confidence: f.confidence,
    face_count: f.face_count,
    age_group: f.age_group,
  }));

  const csv = Papa.unparse(rows);
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `bias_report_${report.id}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadPDF(report) {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;

  // Title
  doc.setFontSize(20);
  doc.setTextColor(99, 102, 241);
  doc.text('Multimodal Bias Detection Report', margin, y);
  y += 10;

  // Subtitle
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated: ${new Date(report.created_at).toLocaleString()}`, margin, y);
  y += 6;
  doc.text(`Media: ${report.media_name} (${report.media_type})`, margin, y);
  y += 12;

  // Divider
  doc.setDrawColor(51, 65, 85);
  doc.line(margin, y, 210 - margin, y);
  y += 10;

  // Summary
  doc.setFontSize(14);
  doc.setTextColor(241, 245, 249);
  doc.text('Summary Metrics', margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(99, 102, 241);
  doc.text(`Bias Score: ${(report.bias_score * 100).toFixed(1)}%`, margin, y);
  y += 6;
  doc.text(`Representation Index: ${(report.representation_index * 100).toFixed(1)}%`, margin, y);
  y += 6;
  doc.text(`Average Confidence: ${(report.avg_confidence * 100).toFixed(1)}%`, margin, y);
  y += 6;
  doc.text(`Gender Distribution — Male: ${report.gender_distribution.male}, Female: ${report.gender_distribution.female}`, margin, y);
  y += 12;

  // Divider
  doc.setDrawColor(51, 65, 85);
  doc.line(margin, y, 210 - margin, y);
  y += 10;

  // Frame analysis
  doc.setFontSize(14);
  doc.setTextColor(241, 245, 249);
  doc.text('Frame-by-Frame Analysis', margin, y);
  y += 8;

  doc.setFontSize(9);
  report.frames.forEach((frame) => {
    if (y > 270) {
      doc.addPage();
      y = margin;
    }
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Screen ${frame.screen_id}${frame.timestamp ? ` [${frame.timestamp}]` : ''} | ${frame.gender.toUpperCase()} | ${frame.role} | ${frame.activity} | ${frame.emotion} | Conf: ${(frame.confidence * 100).toFixed(0)}%`,
      margin, y
    );
    y += 6;
  });

  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by Multimodal Bias Detection & Reporting System', margin, y);

  doc.save(`bias_report_${report.id}.pdf`);
}

export function getSeverityLevel(biasScore) {
  if (biasScore <= 0.2) return { label: 'Low', color: '#10B981', bg: 'rgba(16,185,129,0.1)', border: 'rgba(16,185,129,0.3)' };
  if (biasScore <= 0.5) return { label: 'Moderate', color: '#F59E0B', bg: 'rgba(245,158,11,0.1)', border: 'rgba(245,158,11,0.3)' };
  return { label: 'High', color: '#EF4444', bg: 'rgba(239,68,68,0.1)', border: 'rgba(239,68,68,0.3)' };
}

export function formatDate(iso) {
  return new Date(iso).toLocaleDateString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

export function capitalize(str) {
  return str ? str.charAt(0).toUpperCase() + str.slice(1) : '';
}
